# Generated by Django 5.2 on 2025-04-12 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('social_nature', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=11)),
                ('revenues', models.FloatField(blank=True, default=0.0)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id_sale', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.CharField(default='', max_length=50)),
                ('supplier', models.CharField(default='', max_length=100)),
                ('price_sale', models.FloatField(default=0.0)),
                ('data', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.category')),
            ],
        ),
    ]
