# Generated by Django 5.2 on 2025-04-12 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_sales_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='data',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='sales',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
